version: 0.2

phases:
  install:
    commands:
      - echo "Setting up SSH"
      - mkdir -p ~/.ssh
      - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  build:
    commands:
      - echo "Build started"

  post_build:
    commands:
      - echo "Deploying to EC2"
      - ssh -o StrictHostKeyChecking=no ubuntu@13.233.111.160 "cd /home/ubuntu/nodejs-cicd-deploy && git pull && npm install && pm2 restart all || pm2 start app.js"